// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MyNewProject.Tests")>]
[<assembly: AssemblyProductAttribute("MyNewProject")>]
[<assembly: AssemblyDescriptionAttribute("MyNewProjectr")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MyNewProject.Tests"
    let [<Literal>] AssemblyProduct = "MyNewProject"
    let [<Literal>] AssemblyDescription = "MyNewProjectr"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
